FROM node:18-alpine

WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install

COPY . /app/
ARG SERVICE_PORT=2115
ENV SERVICE_PORT=${SERVICE_PORT}
EXPOSE ${SERVICE_PORT}

CMD npm run dev -- --host