version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
    - ./:/app
    - ./node_modules
    ports:
      - 3000:3000
    